
services:
  test:
    platform: linux/amd64
    image: hanaik/minerstat:late
    user: root
    command: node /home/minerstat/minerstat-os/start
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]