services:
  test:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: sh cronjob.sh 2022-01-01 2023-01-23
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '3']
              capabilities: [gpu]
