version: '3'
services:

  minerstats:
    platform: linux/amd64
    image: hanaik/minerstat:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

    networks:
      - minerstats


networks:
  minerstats:
    driver: "bridge"