services:
  test:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    command: sh cronjob.sh 06-01-2023 08-01-2023
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '3']
              capabilities: [gpu]
