version: "3"
services:
  test:
    platform: "linux/amd64"
    image: hanaik/minerstat:latest
    user: root
    command: node /home/minerstat/minerstat-os/start
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '3']
              capabilities: [ gpu ]