
services:
  test:
    image: hanaik/minerstat
    user: root
    command: node --max-old-space-size=128 start
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]