#!/bin/bash

echo "Watchdog agent starting.."

# ANPIX USB WatchDog Card
P1=$(lsusb | grep "5131:2007")
# domybest USB Watchdog Card
P2=$(lsusb | grep "1a86:7523")
# ALLOYSEED USB Watchdog
P3=$(lsusb | grep "0471:2379")

# OCTOMINER || MINERDUDE
P4=$(lsusb | grep "16c0:05dc")

if [ ! -z "$P1" ] || [ ! -z "$P2" ] || [ ! -z "$P3" ]; then
  echo "USB Watchdog detected.. Sending signal"
  while true
  do
    sudo su -c "printf '\x1E\x00' >/dev/ttyUSB*"
    sudo su -c "printf '\x1E\x00' >/dev/hidraw*"
    sleep 1
  done
fi

# Open-dev wdt
OWDT=$(ls /dev/ttyACM* 2> /dev/null)
if [ ! -z "$OWDT" ]; then
  echo "Open-dev USB Watchdog detected.. Sending signal"
  while true
  do
    sudo su -c "echo -n '~U' >/dev/ttyACM*"
    sleep 1
  done
fi

if [ ! -z "$P4" ]; then
  echo "Octominer or Minerdude machine detected.. Sending signal"
  timeout 1 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -w 180 -v 360
  while true
  do
    timeout 1 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -s
    sleep 1
  done
fi

echo "No watchdog found / script closed.."
exit 1
