#!/bin/bash

sleep 90

# Check if clocktune applied or not after boot
# If not exec for protection

FILE=/dev/shm/bootclock.pid
if [ -f "$FILE" ]; then
    echo "pid found"
else 
    echo "pid not found"
    sudo bash /home/minerstat/minerstat-os/bin/overclock.sh
fi
