#!/bin/bash

# Read settings
FANMIN=$(cat /media/storage/fans.txt | grep "FANMIN=" | xargs | sed 's/[^0-9]*//g')
FANMAX=$(cat /media/storage/fans.txt | grep "FANMAX=" | xargs | sed 's/[^0-9]*//g')
TARGET=$(cat /media/storage/fans.txt | grep "TARGET_TEMP=" | xargs | sed 's/[^0-9]*//g')

# Navi "2" pwm
PWM=$(cat /dev/shm/fantype.txt | xargs | sed 's/[^0-9]*//g')

if [ -z "$PWM" ]; then
  PWM="1"
fi

# If no settings
if [ -z "$FANMIN" ]; then
  FANMIN=70
  echo "FANMIN has no value [Set to $FANMIN]"
fi

if [ -z "$FANMAX" ]; then
  FANMAX=100
  echo "FANMAX has no value [Set to $FANMAX]"
fi

if [ -z "$TARGET" ]; then
  TARGET=60
  echo "TARGET_TEMP has no value [Set to $TARGET]"
fi

if [ "$FANMIN" = "$FANMAX" ]; then 
  SLEEP=75
else
  SLEEP=20
fi

# Drivers
TEST_NVIDIA=$(nvidia-smi -L)
NUM_AMD=$(sudo lshw -C display | grep AMD | wc -l)
if [ "$NUM_AMD" = "0" ]; then
  NUM_AMD=$(sudo lshw -C display | grep amdgpu | wc -l)
fi
TEST_AMD=$NUM_AMD
if [[ $TEST_NVIDIA == *"GPU 0"* ]]; then
  NVIDIA_FAN_NUM=$(sudo nvidia-settings -c :0 -q fans | grep "fan:" | wc -l)
fi

loop() {
  echo "---------------"
  if [ $NUM_AMD -gt 0 ]; then
    
   #FANMIN n MAX
   FANMIN2=$(echo $FANMIN | cut -f1 -d".")
   FANMIN2=$((FANMIN2 * 2.55))
   FANMIN2=$(printf "%.0f\n" $FANMIN2)
              
   FANMAX2=$(echo $FANMIN | cut -f1 -d".")              
   FANMAX2=$((FANMAX2 * 2.55))
   FANMAX2=$(printf "%.0f\n" $FANMAX2)
  
    QUERY=$(sudo /home/minerstat/minerstat-os/bin/amdinfo)
    TEST_AMD=$NUM_AMD
    if [ ! -z "$QUERY" ]; then
      x="0"
      y="0"
      PARAM=""
      PARAMS=""
      PARAMSAFETY=""
      until [ $TEST_AMD == "$x" ]; do
        if [ ! -f "/sys/class/drm/card$x/device/pp_table" ]; then
          echo "$x not exist, iGPU ?"
          y=$((y+1))
          if [ ! -f "/sys/class/drm/card$y/device/pp_table" ]; then
            y=$((y+1))
            if [ ! -f "/sys/class/drm/card$y/device/pp_table" ]; then
              y=$((y+1))
            fi
          fi
        fi
        TEMP=$(echo $QUERY | /home/minerstat/minerstat-os/bin/jq -r .[\"$x\"] | awk '{print $1}' | sed 's/[^0-9.]*//g' | cut -d. -f1 | xargs)
        FAN=$(echo $QUERY | /home/minerstat/minerstat-os/bin/jq -r .[\"$x\"] | awk '{print $2}' | sed 's/[^0-9.]*//g' | cut -d. -f1 | xargs)
        if [ ! -z "$TEMP" ]; then
          DIFF=$((TARGET-TEMP))
          MSG="COLD >$DIFF C!"
          # Colder than target temp
          if [ $DIFF -gt 1 ]; then
            CHANGE=4
            if [ $DIFF -gt 2 ]; then
              CHANGE=5
            fi
            if [ $DIFF -gt 5 ]; then
              CHANGE=6
            fi
            if [ $DIFF -gt 10 ]; then
              CHANGE=10
            fi
            if [ $DIFF -gt 20 ]; then
              CHANGE=20
            fi
            if [ $DIFF -gt 30 ]; then
              CHANGE=30
            fi
            NEWFAN=$((FAN-CHANGE))
            if [ $NEWFAN -lt $FANMIN2 ]; then
              NEWFAN=$FANMIN
            fi
            # Hotter than target temp
          elif [ $DIFF -lt -1 ]; then
            MSG="WARM >$DIFF C!"
            CHANGE=4
            if [ $DIFF -lt -2 ]; then
              CHANGE=5
            fi
            if [ $DIFF -lt -5 ]; then
              CHANGE=6
            fi
            if [ $DIFF -lt -10 ]; then
              CHANGE=10
            fi
            if [ $DIFF -lt -20 ]; then
              CHANGE=20
            fi
            if [ $DIFF -lt -30 ]; then
              CHANGE=30
            fi
            NEWFAN=$((FAN+CHANGE))
            if [ $NEWFAN -gt $FANMAX2 ]; then
              NEWFAN=$FANMAX
            fi
          else
            # No fan changes needed
            #NEWFAN=$FANMIN
            MSG="ON TARGET"
          fi
          if [ "$MSG" != "ON TARGET" ]; then
            if [ $NEWFAN -gt 100 ]; then
              NEWFAN="100"
            fi
            FANMOD=$((FAN+2))
            if [ ! $FAN -eq $NEWFAN ] && [ ! $FANMOD -eq $NEWFAN ]; then
              PARAM="SET"
              MSG="$MSG,NEWFAN: $NEWFAN%"
            fi
          fi
          if [ ! -z "$PARAM" ]; then
            #sudo nvidia-settings -c :0 $PARAM &> /dev/null
            if [ "$MSG" != "ON TARGET" ]; then
              #MAXFAN=$(cat /sys/class/drm/card$y/device/hwmon/hwmon?/fan1_max)
              #if [ -z "$MAXFAN" ]; then
                MAXFAN=$(cat /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1_max)
              #fi
              CURRFAN=$(cat /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1)
              #if [ -z "$MAXFAN" ]; then
                #MAXFAN=$(cat /sys/class/drm/card$y/device/hwmon/hwmon??/fan1_max)
              #fi
              if [ -z "$MAXFAN" ]; then
                MAXFAN=$(cat /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1_max)
              fi
              if [ -z "$CURRFAN" ]; then
                CURRFAN=$(cat /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1)
              fi
              CURRFANFIVE=$((CURRFAN-5))
              echo "MAXFAN FOR $x $y : $MAXFAN"
              FANVALUE=$(echo - | awk "{print $MAXFAN / 100 * $NEWFAN}" | cut -f1 -d".")
              FANVALUE=$(printf "%.0f\n" $FANVALUE)
              FANVALUE=$(awk -v n="$FANVALUE" 'BEGIN{print int((n+5)/10) * 10}')
              #FANVALUE=$((FANVALUE - 1))
              if [ $NEWFAN -gt 99 ]; then
                FANVALUE=$MAXFAN
              fi
              #if [ "$CURRFAN" != "$FANVALUE" ]; then
              if [ "$CURRFAN" != "$FANVALUE" ] && [ "$CURRFANFIVE" != "$FANVALUE" ]; then
                if [ "$PWM" = "1" ]; then
                  sudo su -c "echo 1 > /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1_enable"
                  sudo su -c "echo $FANVALUE > /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1"
                  sudo su -c "echo 1 > /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1_enable" >/dev/null 2>&1
                  sudo su -c "echo $FANVALUE > /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1" >/dev/null 2>&1
                  #sudo /home/minerstat/minerstat-os/bin/rocm-smi --setfan $FANVALUE -d $y &
                  #sudo /home/minerstat/minerstat-os/bin/rocm-smi -d $y --setfan $FANVALUE
                else
                  sudo su -c "echo 2 > /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1_enable"
                  sudo su -c "echo 1 > /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1_enable"
                  sudo su -c "echo 255 > /sys/class/drm/card$y/device/hwmon/hwmon?/pwm1"
                  sudo su -c "echo 2 > /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1_enable" >/dev/null 2>&1
                  sudo su -c "echo 1 > /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1_enable" >/dev/null 2>&1
                  sudo su -c "echo 255 > /sys/class/drm/card$y/device/hwmon/hwmon??/pwm1" >/dev/null 2>&1
                fi
              fi
            fi
            if [ ! -z "$PARAM" ]; then
              MSG="$MSG,CURRVAL: $CURRFAN, WANT: $NEWFAN %,FANVAL: $FANVALUE val"
            fi
          fi
        else
          if [ ! -f "/sys/class/drm/card$x/device/pp_table" ]; then
            echo "$x not exist, iGPU ?"
            if [ $TEST_AMD -gt 16 ];then
              x=$TEST_AMD
            fi
            TEST_AMD=$((TEST_AMD+1))
          fi
        fi
        echo "GPU$x [RID: $y] [$TEMP C / $FAN% ] [MSG:$MSG]"
        x=$((x+1))
        y=$((y+1))
      done
    fi
  fi
  if [[ $TEST_NVIDIA == *"GPU 0"* ]]; then
    # Check XSERVER
    SNUMD=$(sudo su minerstat -c "screen -list | grep -c display2")
    if [ "$SNUMD" = "0" ]; then
      sudo su minerstat -c "screen -A -m -d -S display2 sudo X"
    fi
    NVIDIA_NUM=$(nvidia-smi --query-gpu=count --format=csv,noheader | tail -n1 | xargs | sed 's/[^0-9]*//g')
    NVIDIA_INUM=$((NVIDIA_NUM-1))
    NVIDIA2X=$((NVIDIA_NUM*2))
    PARAM=""
    PARAMS=""
    PARAMSAFETY=""
    x="0"
    z="0"
    if [ -z "$NVIDIA_NUM" ]; then
     #sudo nvidia-smi --query-gpu=count --format=csv,noheader | grep "lost"
     echo "SEEMS NVIDIA DRIVER CRASHED - REBOOT REQUIRED !!"
     NVIDIA_NUM=0
     else
     echo "FAN NUM: $NVIDIA_FAN_NUM"
    fi
    until [ $NVIDIA_NUM == "$x" ]; do
      TEMP=$(nvidia-smi -i $x --query-gpu=temperature.gpu --format=csv,noheader | tail -n1 | xargs | sed 's/[^0-9]*//g')
      FAN=$(nvidia-smi -i $x --query-gpu=fan.speed --format=csv,noheader | tail -n1 | xargs | sed 's/[^0-9]*//g')
      if [ ! -z "$TEMP" ]; then
        DIFF=$((TARGET-TEMP))
        MSG="COLD >$DIFF C!"
        # Colder than target temp
        if [ $DIFF -gt 1 ]; then
          CHANGE=4
          if [ $DIFF -gt 2 ]; then
            CHANGE=5
          fi
          if [ $DIFF -gt 5 ]; then
            CHANGE=6
          fi
          if [ $DIFF -gt 10 ]; then
            CHANGE=10
          fi
          if [ $DIFF -gt 20 ]; then
            CHANGE=20
          fi
          if [ $DIFF -gt 30 ]; then
            CHANGE=30
          fi
          NEWFAN=$((FAN-CHANGE))
          if [ $NEWFAN -lt $FANMIN ]; then
            NEWFAN=$FANMIN
          fi
          # Hotter than target temp
        elif [ $DIFF -lt -1 ]; then
          MSG="WARM >$DIFF C!"
          CHANGE=5
          if [ $DIFF -lt -2 ]; then
            CHANGE=8
          fi
          if [ $DIFF -lt -5 ]; then
            CHANGE=11
          fi
          if [ $DIFF -lt -10 ]; then
            CHANGE=15
          fi
          if [ $DIFF -lt -20 ]; then
            CHANGE=20
          fi
          if [ $DIFF -lt -30 ]; then
            CHANGE=30
          fi
          NEWFAN=$((FAN+CHANGE))
          if [ $NEWFAN -gt $FANMAX ]; then
            NEWFAN=$FANMAX
          fi
        else
          # No fan changes needed
          #NEWFAN=$FANMIN
          MSG="ON TARGET"
        fi
        if [ "$MSG" != "ON TARGET" ]; then
          if [ $NEWFAN -gt 100 ]; then
            NEWFAN="100"
          fi
          if [ ! $FAN -eq $NEWFAN ]; then
              sudo /home/minerstat/minerstat-os/core/nv_fanid $x
              ID1=$(cat /dev/shm/id1.txt | xargs) 
              ID2=$(cat /dev/shm/id2.txt | xargs)
              
              if [ -z "$ID1" ] && [ -z "$ID2" ]; then
                PARAM="$PARAM -a [gpu:$x]/GPUFanControlState=1"
                PARAMS="$PARAMS -a [fan:"$z"]/GPUTargetFanSpeed="$NEWFAN""
                if [ "$NVIDIA_FAN_NUM" -gt "$NVIDIA_NUM" ]; then
                  edit=$((z+1))
                  PARAMSAFETY="$PARAMSAFETY -a [fan:"$edit"]/GPUTargetFanSpeed="$NEWFAN""
                fi   
              else
                PARAM="$PARAM -a [gpu:$x]/GPUFanControlState=1"
                PARAMS="$PARAMS -a [fan:"$ID1"]/GPUTargetFanSpeed="$NEWFAN""
                #PARAMSAFETY=""
                 if [ ! -z "$ID2" ]; then
                 PARAM="$PARAM -a [gpu:$x]/GPUFanControlState=1"
                 PARAMS="$PARAMS -a [fan:"$ID2"]/GPUTargetFanSpeed="$NEWFAN""
                 #PARAMSAFETY=""
                fi  
              fi
            MSG="$MSG,NEWFAN: $NEWFAN%"
          fi
        fi
        echo "GPU$x [$TEMP C / $FAN%] [MSG:$MSG]"
      fi
      x=$((x+1))
      y=$((y+1))
      if [ "$NVIDIA_FAN_NUM" -gt "$NVIDIA_NUM" ]; then
        z=$((z+1))
      fi
      z=$((z+1))
    done
     if [ ! -z "$PARAM" ]; then
      sudo su -c "nvidia-settings -c :0 $PARAM $PARAMS $PARAMSAFETY"
     fi
  fi

  sleep $SLEEP
  loop

}

loop