#!/bin/bash

# MODIFY NETWORK.TXT
sudo sed -i '/IPADDRESS/d' /media/storage/network.txt
sudo sed -i '/NETMASK/d' /media/storage/network.txt
sudo sed -i '/GATEWAY/d' /media/storage/network.txt
sudo sed -i '/DHCP/d' /media/storage/network.txt
sudo echo "" >> /media/storage/network.txt
sudo echo 'IPADDRESS=""' >> /media/storage/network.txt
sudo echo 'NETMASK=""' >> /media/storage/network.txt
sudo echo 'GATEWAY=""' >> /media/storage/network.txt
sudo echo 'DHCP="YES"' >> /media/storage/network.txt

# RUN STATIC SCRIPT
sudo /home/minerstat/minerstat-os/bin/dhcp.sh

# CHECK IPV4
if ping -q -c 1 -W 1 1.1.1.1 >/dev/null; then
  echo
  echo "Ipv4 is up"
  echo
else
  echo
  echo "IPv4 is down"
  echo
fi

sleep 3

# CHECK DNS
TEST="$(ping api.minerstat.com. -w 1 | grep '1 packets transmitted')"
if echo "$TEST" | grep "0%" ;then
  echo ""
  echo "Success! You have active internet connection."
else
  echo ""
  echo "Oh! Something went wrong, you are not connected to the internet."
fi
echo
