#!/bin/bash

sudo systemctl disable systemd-resolved &
sudo systemctl stop systemd-resolved &

# check cloudflare ips
SERVERA="104.20.2.95"
SERVERB="104.20.3.95"
SERVERC="$SERVERB"
DNSA=$(ping -c 1 $SERVERA &> /dev/null && echo success || echo fail)
if [ "$DNSA" = "success" ]; then
    SERVERC="$SERVERA"
fi
# /etc/hosts
HCHECK=$(cat /etc/hosts | grep "$SERVERC minerstat.com" | xargs)
WCHECK=$(cat /etc/hosts | grep "127.0.1.1 $WNAME" | xargs)
if [ "$HCHECK" != "$SERVERC minerstat.com" ] || [ "$WCHECK" != "127.0.1.1 $WNAME" ]; then
sudo echo "
127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.1.1 $WNAME
$SERVERC minerstat.com
$SERVERC api.minerstat.com
104.24.98.231 static-ssl.minerstat.farm
68.183.74.40 eu.pool.ms
167.71.240.6 us.pool.ms
68.183.74.40 eu.sandbox.pool.ms
167.71.240.6 us.sandbox.pool.ms
162.159.200.1 ntp.ubuntu.com
" > /etc/hosts
fi

NSCHECK=$(cat /etc/resolv.conf | grep "nameserver 1.1.1.1" | xargs)
if [ "$NSCHECK" != "nameserver 1.1.1.1" ]; then
  sudo su -c "echo -n > /etc/resolv.conf; echo 'nameserver 1.1.1.1' >> /etc/resolv.conf; echo 'nameserver 1.0.0.1' >> /etc/resolv.conf; echo 'nameserver 8.8.8.8' >> /etc/resolv.conf; echo 'nameserver 8.8.4.4' >> /etc/resolv.conf; echo 'nameserver 114.114.114.114' >> /etc/resolv.conf; echo 'nameserver 114.114.115.115' >> /etc/resolv.conf; echo nameserver 2606:4700:4700::1111 >> /etc/resolv.conf; echo nameserver 2606:4700:4700::1001 >> /etc/resolv.conf" 2>/dev/null
fi
GET_GATEWAY=$(timeout 5 route -n -e -4 | awk {'print $2'} | grep -vE "0.0.0.0|IP|Gateway" | head -n1 | xargs)
if [ ! -z "$GET_GATEWAY" ]; then
	GCHECK=$(cat /etc/resolv.conf | grep "nameserver $GET_GATEWAY" | xargs)
	if [ "GCHECK" != "nameserver $GET_GATEWAY" ]; then
		sudo su -c "echo 'nameserver $GET_GATEWAY' >> /etc/resolv.conf" 2>/dev/null
	fi
fi
