#!/bin/bash

# To keep libs inside screen too
cd /home/minerstat/minerstat-os/core/

echo "Waiting 10..."
sleep 10

# Control timers
#LOCK_DELAY=$(cat /dev/shm/env_clk_delay.txt 2>/dev/null | xargs)
#if [[ -z "$LOCK_DELAY" ]]; then
#  LOCK_DELAY=40
#fi

# Check for miner running
TEST=$(sudo screen -list | grep -wc minew)

until [ $TEST = 1 ]; do
  TEST=$(sudo screen -list | grep -wc minew)
  echo "Waiting miner to start..."
  sleep 1
done
# Miner up and running
echo "Miner started - 20 sec until applying clocks"
sleep 10
echo "Miner started - 10 sec until applying clocks"
sleep 10
echo "Working on it..."

sudo chmod 777 /dev/shm/amd_vddcache.txt
sudo awk '!a[$0]++' /dev/shm/amd_vddcache.txt >/dev/shm/amd_vddcache_unique.txt
sleep 1
sudo awk '!a[$0]++' /dev/shm/amd_vddcache.txt >/dev/shm/amd_vddcache_unique.txt
sleep 1
sudo chmod 777 /dev/shm/amd_vddcache_unique.txt

cat /dev/shm/amd_vddcache_unique.txt
READIN=$(cat /dev/shm/amd_vddcache_unique.txt)
JOB=""

echo "Appling vddgfx per gpu basis"
while read line; do
  CORECLOCK=$(echo $line | rev | cut -d: -f1 | rev | awk -F'-' '{print $1}')
  VDDC=$(echo $line | rev | cut -d: -f1 | rev | awk -F',' '{print $1}' | awk -F'-' '{print $2}')
  MEMCLOCK=$(echo $line | rev | cut -d: -f1 | rev | awk -F',' '{print $2}')
  GPUID=$(echo $line | cut -d: -f1)
  if [[ "$CORECLOCK" != "skip" ]]; then
    echo "Applying $VDDC mV for $CORECLOCK Mhz (Memoryclock: $MEMCLOCK Mhz) on GPU #$GPUID"
    sudo /home/minerstat/.local/bin/upp -p /sys/class/drm/card$GPUID/device/pp_table vddgfx $CORECLOCK $VDDC --write

    # Apply
    echo "GPU$GPUID : CORECLOCK => $CORECLOCK Mhz ($VDDC mV)"

    sudo /home/minerstat/minerstat-os/bin/msos_od_clk $GPUID "s 1 $CORECLOCK"
    sudo /home/minerstat/minerstat-os/bin/msos_od_clk $GPUID "vc 2 $CORECLOCK"

    sudo su -c "echo 1 > /sys/class/drm/card$GPUID/device/pp_dpm_sclk"
    sudo su -c "echo 2 > /sys/class/drm/card$GPUID/device/pp_dpm_sclk"

    echo "GPU$GPUID : MEMCLOCK => $MEMCLOCK Mhz"
    sudo /home/minerstat/minerstat-os/bin/msos_od_clk $GPUID "m 1 $MEMCLOCK"
    sudo /home/minerstat/minerstat-os/bin/msos_od_clk $GPUID "m 2 $MEMCLOCK"
    sudo /home/minerstat/minerstat-os/bin/msos_od_clk $GPUID "m 3 $MEMCLOCK"

    sudo su -c "echo 2 > /sys/class/drm/card$GPUID/device/pp_dpm_mclk"
    sudo su -c "echo 1 > /sys/class/drm/card$GPUID/device/pp_dpm_mclk"
    sudo /home/minerstat/minerstat-os/bin/msos_od_clk $GPUID "c"

    # Refresh
    sudo su -c "echo '0' > /sys/class/drm/card$GPUID/device/pp_sclk_od"
    sudo su -c "echo '1' > /sys/class/drm/card$GPUID/device/pp_sclk_od"

  fi
done </dev/shm/amd_vddcache_unique.txt
