#!/bin/bash
# Update to 5.4.0-48-generic

CURRENT_KERNEL=$(uname -r)

if [[ $CURRENT_KERNEL == *"5.0.21"* ]]; then

  echo "Updating to 5.4.0 from 5.0.21 ..."
  echo "If the installation asks for user input select ok/yes in every case."

  sleep 5

  export DEBIAN_FRONTEND=noninteractive DEBIAN_FRONTEND=noninteractive
  apt-get \
    -o Dpkg::Options::=--force-confold \
    -o Dpkg::Options::=--force-confdef \
    -y --allow-downgrades --allow-remove-essential --allow-change-held-packages linux-image-5.4.0-48-generic linux-headers-5.4.0-48-generic  linux-modules-extra-5.4.0-48-generic 
  apt-get \
    -o Dpkg::Options::=--force-confold \
    -o Dpkg::Options::=--force-confdef \
    -y --allow-downgrades --allow-remove-essential --allow-change-held-packages *5.0.21*
   sudo rm -rf /lib/modules/5.0.21-050021-generic
   sudo update-grub2
   sudo update-initramfs -u
   sync

else
  echo "Already Updated / No update available"
fi
