#!/bin/bash
exec 2>/dev/null

miner=$1
query=$(pidof $miner)

echo "$query" | while IFS= read -r line ; do
  IFS=' ' read -ra NAMES <<< "$line"
  sudo kill -9 ${NAMES[0]}
  sudo kill -9 ${NAMES[1]}
  sudo kill -9 ${NAMES[2]}
  sudo kill -9 ${NAMES[3]}
done

# Octominer clear error led on miner start
if [[ -f "/dev/shm/octo.pid" ]]; then
  # -l ID, -v 0=off, 1=on, 2=blink 0.1s, 3=blink 1s, >=4=blink 3s
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -l 0 -v 0
fi
