#!/bin/bash

if [ -z "$1" ] && [ -z "$2" ]; then
  echo "Usage: maccesskey ACCESSKEY"
  echo "This command is only recommended to use for moving the same rig to a sub-account."
  exit 1
fi

if [ -z "$1" ]; then
  echo "ACCESSKEY can't be empty"
  exit 1
fi


TOKEN="$(cat /media/storage/config.js | grep 'global.accesskey' | sed 's/global.accesskey =//g' | sed 's/;//g' | sed 's/ //g' | sed 's/"//g' | sed 's/\\r//g' | sed 's/[^a-zA-Z0-9]*//g')"
WORKER="$(cat /media/storage/config.js | grep 'global.worker' | sed 's/global.worker =//g' | sed 's/;//g' | sed 's/ //g' | sed 's/"//g' | sed 's/\\r//g')"


echo "Old AccessKey: $TOKEN"
echo "New AccessKey: $1"
echo "Worker: $WORKER"

echo
sudo su -c "echo 'stop' > /tmp/stop.pid"
sudo node /home/minerstat/minerstat-os/stop.js
sudo su minerstat -c "screen -X -S minerstat-console quit";
sudo su -c "sudo screen -X -S minew quit"

sudo echo global.accesskey = '"'$1'";' > /media/storage/config.js
sudo echo global.worker = '"'$WORKER'";' >> /media/storage/config.js
sudo cp /media/storage/config.js /home/minerstat/minerstat-os/


echo "Validate Config..."
echo

sudo cat /media/storage/config.js

echo "Reinitalize, hostname etc.."
echo

sudo bash /home/minerstat/minerstat-os/bin/hostfix.sh
sudo bash /home/minerstat/minerstat-os/bin/jobs.sh

echo "Applying ClockTune Profile"
echo

sudo bash /home/minerstat/minerstat-os/bin/overclock.sh

echo
echo
echo "You are done !"
echo "Start mining with: mstart"

sync
