#!/bin/bash

# Toggle

if [ -f "/dev/shm/maintenance.pid" ]; then
    echo "STATUS: ENABLED"
    echo "Disabling maintenance mode.."

    sudo rm /dev/shm/maintenance.pid

    echo ""
    echo "Disabled, you can start mining with mstart command."
else 
    echo "STATUS: DISABLED"
    echo "Enabling maintenance mode.."

    sudo echo "null" > /dev/shm/maintenance.pid

    echo ""
    echo "Enabled, remote commands disabled until reboot or mstart."
fi
