#!/bin/bash

echo "$1"
echo "$2"
echo "$3"

if [ -z "$1" ] && [ -z "$2" ] && [ -z "$3" ]; then
  echo
  echo "Usage: static LOCALIP NETMASK GATEWAY"
  echo "e.g: static 192.168.0.100 255.255.255.0 192.168.0.1"
  echo
  exit 0
else
  echo "Please, confirm. Press: [ A ] to accept, [ C ] to reject"
  echo; read -rsn1 -p "Press any key to continue . . ." keypress; echo

  if [ "$keypress" = "a" ] || [ "$keypress" = "A" ]; then
    echo
    echo "Accepted"
    sudo cp -rf /etc/network/interfaces /etc/network/interfaces.bak
    # MODIFY NETWORK.TXT
    sudo sed -i '/IPADDRESS/d' /media/storage/network.txt
    sudo sed -i '/NETMASK/d' /media/storage/network.txt
    sudo sed -i '/GATEWAY/d' /media/storage/network.txt
    sudo echo "" >> /media/storage/network.txt
    sudo echo 'IPADDRESS="'$1'"' >> /media/storage/network.txt
    sudo echo 'NETMASK="'$2'"' >> /media/storage/network.txt
    sudo echo 'GATEWAY="'$3'"' >> /media/storage/network.txt
    # RUN STATIC SCRIPT
    sudo /home/minerstat/minerstat-os/bin/static.sh
    # CHECK IPV4
    if ping -q -c 1 -W 1 1.1.1.1 >/dev/null; then
      echo
      echo "Ipv4 is up"
      echo
    else
      echo
      echo "IPv4 is down"
      echo
    fi
    # CHECK DNS
    TEST="$(ping api.minerstat.com. -w 1 | grep '1 packets transmitted')"
    if echo "$TEST" | grep "0%" ;then
      echo ""
      echo "Success! You have active internet connection."
    else
      echo ""
      echo "Oh! Something went wrong, you are not connected to the internet."
    fi
    echo
  else
    echo
    echo "Cancelled"
    echo
  fi

fi

exit 9
