#!/bin/bash

#####################################
#    BUILD JSON FROM FAN NUMBERS
#####################################

JSON_FAN='{'

for i in {0..15}
do
  JSON_FAN=$JSON_FAN'"'$i'":'

  CHECKTYPE=$(nvidia-smi -L | grep "GPU $i")

  if [[ $CHECKTYPE == *"RTX"* ]]; then
    FANNUM="2"
  elif [[ $CHECKTYPE == *"GTX"* ]]; then
    FANNUM="1"
  else
    FANNUM="0"
  fi

  if [[ $i == "15" ]]; then
    COMMA=""
  else
    COMMA=","
  fi
  JSON_FAN=$JSON_FAN'"'$FANNUM'"'$COMMA''
done

JSON_FAN=$JSON_FAN'}'

echo "DEBUG JSON:"
echo $JSON_FAN
echo

#########################################
#     CHECK FAN POSITION FOR GPUID
#########################################

JQ_PATH="/home/minerstat/minerstat-os/bin/jq"

echo "JQ JSON: "
echo $JSON_FAN | $JQ_PATH -r
echo

SNUM=4
SUM=0

for i in {0..15}
do
  TFAN=$(echo $JSON_FAN | $JQ_PATH -r .[\"$i\"])
  SUM=$((SUM + TFAN))

  # Break the search if target reached
  if [ "$SNUM" = "$i" ]; then
    break
  fi
done

SFAN=$(echo $JSON_FAN | $JQ_PATH -r .[\"$SNUM\"])

if [ "$SFAN" = "2" ]; then
  echo "Searched card is RTX, it has two fan to control"
  ID1=$((SUM - 1))
  ID2=$SUM
  echo "Fan1 ID: $ID1 , Fan2 ID: $ID2"
else
  echo "Searched card is GTX, it has only one fan to control"
  ID1=$SUM
  echo "Fan ID: $ID1"
fi
