#!/bin/bash

version=`cat /etc/lsb-release | grep "DISTRIB_RELEASE=" | sed 's/[^.0-9]*//g'`
if [ "$version" = "1.4" ]; then
  echo "Updating drivers.."
  echo "- Mining Stopped!"
  sudo node /home/minerstat/minerstat-os/stop.js
  sudo su minerstat -c "screen -X -S minerstat-console quit"
  echo "stop" > /tmp/stop.pid
  sudo su -c "sudo screen -X -S minew quit"
  echo 
  echo "Waiting (5 SECONDS...)"
  sleep 5
  echo
  echo
  sudo apt-get update
  sudo apt --fix-broken install -y
  sudo apt-get upgrade -y
  sudo update-initramfs -u
  #sudo update-grub2
  sudo dkms install -m nvidia -v $(ls /usr/src | grep nvidia | sed 's/[nvidia][nvidia}]*//' | sed 's/[-][-}]*//')
  echo "Rebooting.."
  sleep 5
  sudo reboot -f
elif [ "$version" = "1.4.5" ]; then
  echo "Drivers are up to date"
  exit 1
else
elif [ "$version" = "1.4.9" ]; then
  echo "Update to: nvidia 450.57"
  echo "We will make this possible shorty. Try again later."
  exit 1
else
  echo "Currently nvidia-update disabled. Reflash the os to switch between nvidia versions."
  exit 1
fi

  exit 2
if ! grep -q experimental "/etc/lsb-release"; then
  echo "Driver update not supported on your msos version. Please, reflash to be able to use recent nvidia drivers."
  exit 1
fi

echo "- Updating database.. Please, wait"
sudo apt-get update
echo
echo "- Version DB Updated"

ALL_VERSION=$(apt-cache search nvidia | grep -P '^nvidia-[0-9]+\s' | grep "nvidia-" | grep "version" | sed 's/\ .*/ /' | sed 's/[^0-9]*//g')
LAT_VERSION=$(echo $ALL_VERSION | sed 's/.* //' | sed 's/[^0-9]*//g')
CUR_VERSION=$(dpkg -l | grep "NVIDIA binary driver" | awk '{ print $2 }' | xargs | sed 's/[^0-9]*//g')

echo "-------- NVIDIA-UPDATER -----------"
echo

echo "- AVAILABLE NVIDIA VERSIONS:" $ALL_VERSION
echo "- INSTALLED NVIDIA VERSION : $CUR_VERSION"
echo "- LATEST    NVIDIA VERSION : $LAT_VERSION"
echo

rebt () {
  sync
  sleep 10
  sudo reboot -f
}

if [ -z "$1" ]; then
  echo "Please, provide a version to install."
  echo "e.g: nvidia-update $LAT_VERSION"
  echo
else
  re='^[0-9]+$'
  if ! [[ $1 =~ $re ]] ; then
    echo "ERROR: You only can ENTER numbers" >&2; exit 1
  else
    if [[ $ALL_VERSION == *"$1"* ]]; then
      echo "SELECTED VERSION: $1"
      # Stop mining
      echo
      echo "- Mining Stopped!"
      sudo node /home/minerstat/minerstat-os/stop.js
      sudo su minerstat -c "screen -X -S minerstat-console quit"
      echo "stop" > /tmp/stop.pid
      sudo su -c "sudo screen -X -S minew quit"
      echo 
      echo "Waiting (5 SECONDS...)"
      sleep 5
      echo
      echo
      if [ "$1" = "$CUR_VERSION" ]; then
        echo "WARN: This version is already installed.."
        echo "Checking for updates..."
        sleep 1
        sudo apt --fix-broken install -y
        sudo apt-get install nvidia-$1 -y
        echo
        echo "Rebooting in 10 seconds ..."
        rebt
      else
        echo "-----------------------------------"
        echo "1] Disabling Active kernels"
        echo "-----------------------------------"
        sudo su -c "rmmod -f nvidia_uvm; rmmod -f nvidia_drm; rmmod -f nvidia_modeset; rmmod -f nvidia"
        echo "-----------------------------------"
        echo "2] Removing Current version"
        echo "-----------------------------------"
        sudo apt --fix-broken install -y
        sudo apt-get purge nvidia-$CUR_VERSION nvidia-opencl-icd-$CUR_VERSION nvidia-settings -y
        echo "-----------------------------------"
        echo "3] Installing new version"
        echo "-----------------------------------"
        sudo apt-get install nvidia-$1 -y
        echo "-----------------------------------"
        echo "4] Activating new kernel modules"
        echo "-----------------------------------"
        sudo dkms install -m nvidia -v $(ls /usr/src | grep nvidia | sed 's/[nvidia][nvidia}]*//' | sed 's/[-][-}]*//')
        echo "-----------------------------------"
        echo "5] Update initram-fs"
        echo "-----------------------------------"
        sudo update-initramfs -u
        echo "-----------------------------------"
        echo "6] Reboot"
        echo "-----------------------------------"
        rebt
      fi
    else
      echo "ERROR: Invalid version"
    fi
  fi
fi

echo "-----------------------------------"
