#!/bin/bash

# Hello
echo
echo "========== Octominer | minerdude =========="
echo "This tool helps to control chassis fans and leds."
echo

# Reset
Color_Off='\033[0m' # Text Reset

# Regular Colors
Red='\033[0;31m' # Red
Green='\033[0;32m' # Green
Yellow='\033[0;33m' # Yellow

function printfo() {
 mark="i"
 if [[ "$1" = "info" ]]; then
 mark="INFO"
 elif [[ "$1" = "fail" ]]; then
 mark="$Red"'FAIL'"$Color_Off"
 elif [[ "$1" = "ok" ]]; then
 mark="$Green OK $Color_Off"
 elif [[ "$1" = "warn" ]]; then
 mark="$Yellow"'WARN'"$Color_Off"
 fi
 echo -n ""
 echo -e " [$mark] $2 \r"
 echo -n ""
}

# Arg parser
PARAMS=""
ID=""
VAL=""
MIN=""
SAVE_VAL="0"
LIST_VAL="0"

###############
##
## FUNCTIONS
##
##

help () {
  echo
  echo "==== Help ===="
  echo "-h  | --help         : Printing this menu"
  echo "-d  | --display      : Update info display"
  echo "-s  | --shutdown     : Shutdown via chassis"
  echo "-r  | --reboot       : Reboot via chassis"
  echo "-p  | --ping         : Blink blue light for x minutes. (e.g: octo-ping --min 5)"
  echo "-f  | --fan          : Control chasis fans. (e.g: octo-fan --id 1 --val 200)"
  echo "    | --save         : Save fan value and apply on boot"
  echo "    | --list         : List saved fan values on console"
  echo "    | --clear        : Remove all saved fan values"
  echo
  exit 255
}

odetect () {
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -h > /dev/shm/octo_cache.txt 2>&1
  VALIDATE=$(sudo cat /dev/shm/octo_cache.txt)
  if [[ $VALIDATE == *"libusb-0.1"* ]]; then
    if [[ ! -f "/tmp/libusb-0.1-4_0.1.12-31_amd64.deb" ]]; then
      wget https://static-ssl.minerstat.farm/miners/libusb-0.1-4_0.1.12-31_amd64.deb -P /tmp
    fi
    sudo dpkg --force-all -i /tmp/libusb-0.1-4_0.1.12-31_amd64.deb
    timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -h > /dev/shm/octo_cache.txt 2>&1
    VALIDATE=$(sudo cat /dev/shm/octo_cache.txt)
  fi
  if [[ $VALIDATE != *"cannot"* ]]; then
    echo "true"
    sudo echo "true" > /dev/shm/octo.pid
    timeout 5 sudo /home/minerstat/minerstat-os/core/octoctrl --display
  fi
}

odisplay () {
  # Collect Data
  WORKER="$(timeout 5 cat /home/minerstat/minerstat-os/config.js | grep 'global.worker' | sed 's/global.worker =//g' | sed 's/;//g' | sed 's/"//g')"
  IP=`ifconfig | grep "inet" | grep -v "inet6" | grep -vE "127.0.0.1|169.254|172.17." | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | head -n 1 | grep -o -E '[.0-9]+'`
  PID=$(timeout 5 sudo ls /var/run/screen/S-root | grep minew | sed 's/[^0-9]*//g')
  MINER=$(timeout 5 sudo pstree $PID | xargs | rev | cut -d+ -f1 | rev | cut -d* -f1 | sed "s/[^a-zA-Z']/ /g" | xargs | cut -d " " -f 1)

  timeout 5 sudo su -c "sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -h > /dev/shm/octo_cache.txt"
  timeout 5 sudo su -c "sudo /home/minerstat/minerstat-os/core/gputable > /dev/shm/gputable_cache.txt"

  GTEMP=$(timeout 5 cat /dev/shm/gputable_cache.txt | awk -F'|' '{print $4}' | xargs | sed 's/[^0-9 ]//g' | xargs)
  GFAN=$(timeout 5 cat /dev/shm/gputable_cache.txt | awk -F'|' '{print $5}' | xargs | sed 's/[^0-9 ]//g' | xargs)

  FANMAX=0
  TEMPMAX=0

  for vals in $GTEMP; do
    if [[ "$vals" -gt $TEMPMAX ]]; then
      TEMPMAX=$vals
    fi
  done

  for vals in $GFAN; do
    if [[ "$vals" -gt $FANMAX ]]; then
      FANMAX=$vals
    fi
  done

  FANMAX="$FANMAX%"
  TEMPMAX=$TEMPMAX"°C"

  POWER=$(timeout 5 cat /dev/shm/octo_cache.txt | grep Pac | awk '{print $10}')

  C1=$(timeout 5 sudo cat /dev/shm/octo_cache.txt | grep "Temperatures:" | awk -F' ' '{print $2}')
  C2=$(timeout 5 sudo cat /dev/shm/octo_cache.txt | grep "Temperatures:" | awk -F' ' '{print $2}')

  # Reset
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 0,0,4 -v 0
  # Update Entries
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 1,0,3 -v "$WORKER"
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 1,2,2 -v "$IP"
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 0,4,2 -v "Miner:   $MINER"
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 0,5,2 -v "Power:   $POWER"
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 0,6,2 -v "GPUs:    $TEMPMAX  $FANMAX"
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -o 0,7,2 -v "Chassis: $C1  $C2"
}

# Shutdown via chassis
oshutdown () {
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -p
}

# Print Info
oinfo () {
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -h
}

# Reboot via chassis
oreboot () {
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -x
}

# Flash blue lights
oping () {
  printfo info "Raw: $MIN"
  MIN=$((MIN*60))
  printfo info "Will be turned off after: $MIN second"
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -l 1 -v 2
  screen -A -m -d -S kill_ping sudo /home/minerstat/minerstat-os/core/octoctrl --kping $MIN
}

# Flash red error lights
oerr() {
  sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -l 0 -v 3
}

# Ping Leds
kping () {
  sleep $MIN
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -l 0 -v 0
  timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -l 1 -v 0
}

# List fan speeds
ofan_list() {
    printfo info "Listing Saved FAN Values ..."
    sudo chmod 777 /home/minerstat/octo_fans.txt 2>/dev/null
    if [[ -f "/home/minerstat/octo_fans.txt" ]]; then
      while read line; do
        FAN_VAL=$(echo $line | rev | cut -d: -f1 | rev)
        FAN_ID=$(echo $line | cut -d: -f1)
        printfo ok "Found: FAN #$FAN_ID, VALUE: $FAN_VAL"
      done </home/minerstat/octo_fans.txt
      echo
      printfo info "To Clear All values and start over"
      printfo info "Enter: octo-fan --clear"
    else
      printfo fail "No Fan value found."
    fi
}

# List fan speeds
ofan_boot() {
    printfo info "Listing Saved FAN Values ..."
    sudo chmod 777 /home/minerstat/octo_fans.txt 2>/dev/null
    if [[ -f "/home/minerstat/octo_fans.txt" ]]; then
      while read line; do
        FAN_VAL=$(echo $line | rev | cut -d: -f1 | rev)
        FAN_ID=$(echo $line | cut -d: -f1)
        printfo ok "Found: FAN #$FAN_ID, VALUE: $FAN_VAL"
        timeout 15 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -f $FAN_ID -v $FAN_VAL
        sleep 0.25
      done </home/minerstat/octo_fans.txt
    else
      printfo fail "No Fan value saved."
    fi
}

# Set fan speed and apply
ofan () {
  if [[ "$LIST_VAL" = "0" ]]; then
    # Set fans
    # fan ids: 0-8
    # val range: 0-255
    # echo "db: $ID, $VAL"
    if [[ "$ID" -gt "8" ]] || [[ "$ID" -lt "0" ]]; then
      printfo fail "Invalid ID"
      exit 1
    fi
    if [[ "$VAL" -gt "255" ]] || [[ "$VAL" -lt "0" ]]; then
      printfo fail "Invalid VAL"
      exit 1
    fi
    timeout 5 sudo /home/minerstat/minerstat-os/bin/fan_controller_cli -f $ID -v $VALUE
    echo
    # If saving enabled
    if [[ "$SAVE_VAL" = "1" ]]; then
      READIN=$(cat /home/minerstat/octo_fans.txt 2>/dev/null)
      printfo info "Saving: FAN #$ID, VALUE: $VAL"
      if [[ "$READIN" == *"$ID:"* ]]; then
        printfo warn "Warning: FAN #$ID already had value. Replacing with new one."
        OLD_VAR=$(cat /home/minerstat/octo_fans.txt | grep "$ID:")
        printfo info "Previous: $OLD_VAR"
        printfo info "New: $ID:$VAL"
        sudo chmod 777 /home/minerstat/octo_fans.txt 2>/dev/null
        sudo sed -i "/$ID:/d" /home/minerstat/octo_fans.txt
        sudo echo "$ID:$VAL" >> /home/minerstat/octo_fans.txt
      else
        if [[ ! -z "$ID" ]]; then
          sudo echo "$ID:$VAL" >> /home/minerstat/octo_fans.txt
        else
          printfo fail "Unable to save empty data. Verify your input parameters."
        fi
      fi
      echo
      # List saved values
      ofan_list
    fi
  fi
}

# Clear fan speeds to apply from boot
ofan_clear() {
  printfo info "Clearing Saved Fan Values ..."
  sudo chmod 777 /home/minerstat/octo_fans.txt 2>/dev/null
  sudo echo -n > /home/minerstat/octo_fans.txt
}

##
########
## PARSER
########
##

ISPING=0
ISFAN=0

while (( "$#" )); do
  case "$1" in
    -i|--id)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        ID=$2
        shift 2
      else
        echo
        echo "================="
        echo "Error: Please provide ID" >&2
        echo "================="
        echo
        exit 1
      fi
      ;;
    -v|--val)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        VAL=$2
        shift 2
      else
        echo
        echo "================="
        echo "Error: Please provide VAL" >&2
        echo "================="
        echo
        exit 1
      fi
      ;;
    -m|--min)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        MIN=$2
        shift 2
      else
        echo
        echo "================="
        echo "Error: Please provide MIN" >&2
        echo "================="
        echo
        exit 1
      fi
      ;;
    -k|--kping)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        MIN=$2
        kping
        shift 2
      else
        echo
        echo "================="
        echo "Error: Please provide MIN" >&2
        echo "================="
        echo
        exit 1
      fi
      ;;
    --info)
      oinfo
      shift
      ;;
    -t|--detect)
      odetect
      shift
      ;;
    -h|--help)
      help
      shift
      ;;
    -d|--display)
      odisplay
      shift
      ;;
    -s|--shutdown)
      oshutdown
      shift
      ;;
    -r|--reboot)
      oreboot
      shift
      ;;
    -p|--ping)
      ISPING=1
      shift
      ;;
    -f|--fan)
      ISFAN=1
      shift
      ;;
    --save)
      SAVE_VAL=1
      shift
      ;;
    --clear)
      ofan_clear
      shift
      ;;
    --boot)
      ofan_boot
      shift
      ;;
    --list)
      LIST_VAL=1
      ofan_list
      shift
      ;;
    -*|--*=) # unsupported flags
      echo "================="
      echo "Error: Unsupported flag $1" >&2
      echo "================="
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

# Process after parsing done
if [[ "$ISPING" = "1" ]]; then
  oping
fi
if [[ "$ISFAN" = "1" ]]; then
  ofan
fi
