#!/bin/bash

echo "Validating SSH Keys.."

file="/etc/ssh/ssh_host_dsa_key"
check=$(cat $file)
keyc="MIIBuwIBAAKBgQDTanoMk4GUJ4ySRfYnBkH9NDMSjBDd72PvdVuZ5OlBth19OSaO"

if [[ "$check" == *"$keyc"* ]]; then
  echo "Generating new SSH Keys..."
  sudo rm /etc/ssh/ssh_host_dsa_key
  sudo rm /etc/ssh/ssh_host_rsa_key
  sudo cat /dev/zero | ssh-keygen -t ecdsa -b 384 -q -N "" -f /etc/ssh/ssh_host_dsa_key
  sudo cat /dev/zero | ssh-keygen -t rsa -b 2048 -q -N "" -f /etc/ssh/ssh_host_rsa_key
  sudo systemctl restart sshd
  sudo systemctl status sshd
else
  echo "SSH Keys Already Regenerated.."
fi
